#include <windows.h> //windows.h has to be before tlhelp32.h
#include <tlhelp32.h> //windows.h has to be before tlhelp32.h

#include <iostream>
#include <vector>
#include <unordered_map>
#include <limits>
#include <thread>
#include <chrono>
#include <functional>
#include <bitset>
#include <memory>
#include <iomanip>
#include <initializer_list>
#include <ctime>
#include <filesystem>
#include <shlobj.h>
#include <winerror.h>
#include "metastring.h"

/*
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
The ADVobfuscator does not work for the polyloaded
exe file because it has to be compiled with Od to
keep the junk code and the const expressions don't
work as expected. The passwords will be always seen
in this case. This is mainly for sigbench.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
*/

using namespace std;
using namespace andrivet::ADVobfuscator;  

struct player_entity {
    int team = 2;
const char * MTRUWAZAOY = "THZTZUKGFMQECQZUFOHFPQNWMKMXF";
const char * UAFBLKNYSH = "EBFVOOEWGUMGSTCUDHOINAGSQZBFOGGWAHKPIAXVIAYFHTM";
int IQKQDZKDUM = 2259;
char NYIANPGKIM = 'L';
int KSZMCBKWNT = 8495;
const char * WQSBWHVVUI = "JSYRRNBAWEHGLZYBSCJBUCKDWXEOB";

    int hp = 100;
char HBJPUDKSIL = 'S';
const char * SPKHBYFDTL = "OGHVUUINZFOZEBJEXIJAPBDSOMQC";
char VNWWUVJNIP = 'X';
const char * YTTEPFFSUH = "JKRMDOGIEFXDSRDKFARPTLARIJOYHKKVOSMMCJFYBGTT";
int PBMMUARCSC = 9327;
char AEUAHBUVBP = 'A';
int QIWUTNMSGQ = 7027;
int BMMKSTWPOC = 736;

    double velocity = 9.87;
char XTFZYZAAHV = 'M';
int XJEPGCKMMY = 8102;
char JCITKQOGRI = 'V';
const char * GSIQRHURAG = "JRAIARSZYYRPWRHQRGFMOOKJNUTUEEDODGYBKHNOYJXVP";
int LZKQDKUTHV = 2595;

    string player_id = "UI1874s41Q6w5s4";
const char * GYYUUVCMQS = "GJTRNFRPUKIUKOASTJYDUTMHQA";
char CZMQVGEKUR = 'D';
int CERWKXEOGU = 1094;
char CROKMWLANQ = 'O';
char HTMNFDGAQE = 'W';
const char * DWCKLLHIWD = "ESTXXGCRLPAOQLRICNBSYUOHQUBPBJGTEFIU";
char GIUOMLKCHM = 'Y';
const char * DEUUKQJDMH = "ENQCJHKLCWWWEHEMJEEIHCUY"; 
};
char YUPYRZYFPA = 'V';
char BVXBWYGIPN = 'F';
int AYIYVCSRYX = 3565;
char VEEWXZRDQA = 'D';
char LGGWRWVKOL = 'Y';
  
void memory_modification(void) {;
char AJNIEKDLHF = 'R';
const char * JKQVBNZVZM = "WWZCBYBKGMFXPEVLQAWEBODHLFPMXYXRNVQM";
int IBNFULHEMA = 6459;
int VCIMHSRQVI = IBNFULHEMA - IBNFULHEMA;
char UOJGHYJYHD = 'V';
int YGVPCPFIIT = VCIMHSRQVI + IBNFULHEMA;
int DTQDFCWUBW = 7524;
int EXORQKIRSL = 9572;

    auto player_list = { player_entity(), player_entity() };
char FQTPSEHAZC = 'M';
const char * AVJANFVVCE = "YAPUHPKHRZSXGBMEPBFEUBWPOZQFGDIJAUVPCJAKOVVWH";
const char * CZBAGTXZBX = "ZGIZFBOQIWMFXCFBVPZGZIQWQ";
int FXOMBSYKCD = 6932;
char UHFYBQUEXA = 'R';

    while (true) {;
char CRERQLICVQ = 'B';
const char * VTHMABJJHE = "TJOGWZHWXKRQGFLNGDGYQECFWMRXYISCXSLHBELCNUELEDAH";
char OCGAFIPHIJ = 'K';
int KXPSOSOUDL = 861;
int LVZRBTLKIK = 1967;

        this_thread::sleep_for(chrono::seconds(1));
int SJVZSUAUDW = 5942;
char KMMLCAOVUM = 'P';
int QZXCMJHMAE = 9348;
int RJHZKYLIYX = SJVZSUAUDW - SJVZSUAUDW;
RJHZKYLIYX = SJVZSUAUDW + QZXCMJHMAE;
SJVZSUAUDW = SJVZSUAUDW + QZXCMJHMAE;
int KHOHJTXLMN = 1950;

        for (auto& p : player_list) {;
const char * HAZFEFLFCH = "UHCQNFPENHXRJOZLZULJBRPWAWWFAZYIZWNBQHYG";
const char * AEOKIQQFUL = "QXQDSGPQJKENJORMBYUSWELBNBMRGFAF";
char NRBGKIKRIX = 'N';
const char * QEVREOGZTO = "MPQRTXKEKZZVWPGRPKANHXFWWQACQTFUZF";
char RTQQUYSDWR = 'I';
const char * BXXQOTAFOJ = "UDWINQTFWRAOXYUGPOUJEORYETCRBZZBIZWMXQFMCMM";
int BJZSUNKRUZ = 5988;
BJZSUNKRUZ = BJZSUNKRUZ - BJZSUNKRUZ;

            cout << "ID: " << p.player_id << ", HP: " << p.hp << ", velocity: " << p.velocity << endl;
int XSYGXCHIZI = 2830;
int KXVUKWOOIH = XSYGXCHIZI + XSYGXCHIZI;
char LYAIOPCCBP = 'M';
int MSXEAAIZEF = XSYGXCHIZI - XSYGXCHIZI;
char NGJMWJGJNV = 'U';

        };
const char * VKJCZUQMKA = "DMTVSFFLDNBFVYMDLOQFGQGJUGGKWHACGJJJPLQIQIPFTFODN";
char EYUUTNGKAM = 'Y';
const char * OWNZYLPCOA = "IOXBBPPRCXFCCILQWDEKEJWUSSUGDOKCEALFVMFVLUVWITK";
char MUSYKPTZSD = 'I';
char VJOOMDYBXG = 'V';
char YJZJNZLZHD = 'T';
char VMSOGLMSDW = 'Z';
int GHKFVITGZI = 289;

    };
char KLTSJBRPFS = 'A';
char JVLTCFBJXC = 'F';
char FDZKMJMLRZ = 'W';
const char * TAUUIMBPJU = "NHNWCYRSHGEMFCGDVFPTKYLZCLHBLBPFLR";
char DYMKMAHOTP = 'N';

}

void opcode_injection(void) {;
const char * CIFKUBBOWN = "RRPGGQYBOQDEJVCSDJRKOVOZDVFLJPWGKRSUKAIDQMBB";
const char * EWPRIYFECG = "CQCKKMRYTWTRCIHCBOUBUMAZZQUBRRCHLWRTXXSDVCICK";
int MIAWDPIEAQ = 6367;
MIAWDPIEAQ = MIAWDPIEAQ + MIAWDPIEAQ;
int GGQOEDWQGR = MIAWDPIEAQ - MIAWDPIEAQ;
int UNMZGVBDUN = MIAWDPIEAQ - MIAWDPIEAQ;
MIAWDPIEAQ = UNMZGVBDUN - MIAWDPIEAQ;

      
    int* src = new int[64];
const char * ZTSYJLSOPP = "PMOHMAKOKKQXEBWYPQXYTODOTGI";
char QKFYIFPIRB = 'M';
const char * VDBHJVNWMM = "YRRNBJANFSXYZFSPZLNHOE";
int CPMVEXTLAD = 3261;
CPMVEXTLAD = CPMVEXTLAD - CPMVEXTLAD;
char GEYFBCQGNK = 'Z';
CPMVEXTLAD = CPMVEXTLAD - CPMVEXTLAD;     
 
    int bad_code[] = { 0x83ec8b55,0x565340ec,0x0c758b57,0x8b087d8b,
                       0x348d104d,0xcf3c8dce,0x6f0fd9f7,0x6f0fce04,
                       0x0f08ce4c,0x10ce546f,0xce5c6f0f,0x646f0f18,
                       0x6f0f20ce,0x0f28ce6c,0x30ce746f,0xce7c6f0f,
                       0x04e70f38,0x4ce70fcf,0xe70f08cf,0x0f10cf54,
                       0x18cf5ce7,0xcf64e70f,0x6ce70f20,0xe70f28cf,
                       0x0f30cf74,0x38cf7ce7,0x7508c183,0xf8ae0fad,
                       0x5e5f770f,0x5de58b5b,0xccccccc3 };
char VPMGXURYLY = 'I';
const char * OPBXVDKKTN = "FBAYUMPBTALVXUXAKKDEIFNLPMWVLNEUHYGFWWW";
char WXOWCUDCXC = 'A';
int PIJANPJIPU = 5803;
PIJANPJIPU = PIJANPJIPU - PIJANPJIPU;
int ONRIKRQIUI = 7651;
char NDEYPGSGMO = 'X';     
 
    int* dst_mir = new int[64];
int IALGFOFYLM = 9462;
int XHOZVWFSSM = IALGFOFYLM - IALGFOFYLM;
int ZUGCJPWODF = 6984;
int RFYRXVZXOB = 2202;
int ZRWGFBJMET = RFYRXVZXOB + XHOZVWFSSM;     
 
    int* dst = new int[64];
const char * QEVQAGQRKE = "ELSAZTHXXHYMJSEBEVYNPXRLBHZHSBEWADFBMTWGAMDORRM";
const char * WELWMRIGUG = "SUZEVDCLFMDPLYSNCUCTJVALNPHKJVZHFUDLAHHLPFGLSPAXT";
int FMRMPXTOQG = 8260;
int KNWJRVGMUN = 6587;
FMRMPXTOQG = KNWJRVGMUN - KNWJRVGMUN;      

    for (int i = 0; i < 64; ++i) {
char QFPMPSEFSM = 'Q';
int QXDWYWFIBN = 6718;
const char * AILJEVSQLB = "UAGRMQOZDMAHASQWSGICNFOPKSWNQYKEVGCXPOVLZRHMZB";
char NZAJCZJPMQ = 'G';
const char * AIFBWLUPTG = "LWDWXCQJIEARXABWWNLYIBRZ";
int DPQBUTWYGW = QXDWYWFIBN + QXDWYWFIBN;
char PARHBUPXCH = 'H';
char FDNVRNTSDF = 'X';

        src[i] = i;
int VZKVAYKQBZ = 6431;
char IZSZMMBPAS = 'Z';
const char * MDTMUUGYYP = "GHIKSDEXBIEUZETLANVHKAIMHWPEWOKKJESF";
VZKVAYKQBZ = VZKVAYKQBZ + VZKVAYKQBZ;
char IJTIBJGLCI = 'D';

    }
    void* address = VirtualAlloc(NULL, sizeof(bad_code), MEM_COMMIT | MEM_RESERVE, PAGE_EXECUTE_READWRITE);
const char * WDWOAANXTK = "LNHKQZTIGYDYCHDNHZIBBMGHMAHNBGMOYYWNCWUDPUZAS";
int THWNFYLIUY = 2678;
const char * QRFHZLPZEK = "KLFEMHMGOHGAQNBODPDYGCYDMJMAODFOWHCTTG";
char LAKQKQPTXX = 'M';
int LJINBSDUMR = 4442;
int JLHVWTQNGR = LJINBSDUMR - LJINBSDUMR;

    memcpy(address, bad_code, sizeof(bad_code));
int RRWNLYUGRO = 7506;
const char * IZPRMFIQCQ = "LYDQFIWJAJAUEFSLQBDHZWOXSSBJOKMPBGBMUD";
RRWNLYUGRO = RRWNLYUGRO - RRWNLYUGRO;
int MUURPYIQOK = RRWNLYUGRO + RRWNLYUGRO;
const char * QXLTYDGQMA = "OPEYPOIOPUSWQSQNCPGODFPCRWLMJODFPETAKLQJERX";
int UAIPDBGLRJ = RRWNLYUGRO - RRWNLYUGRO;
int BRNHMYPDQY = MUURPYIQOK + MUURPYIQOK;
int RBKDTKBYDM = 4038;

    __asm {
        push        20h
        mov         eax, dword ptr[src]
        push        eax
        mov         ecx, dword ptr[dst]
        push        ecx
        mov         ecx, dword ptr[address]
        call        ecx
        add         esp, 0Ch
    };
int FYGILWJJTI = 811;
char NDJCFBKWPQ = 'R';
char RPODZONVKZ = 'P';
int GVYTIKHWYP = FYGILWJJTI - FYGILWJJTI;
char HPQAFUUPIN = 'F';

    typedef void (*FASTCALL)(void* dst, void* src, int len);
int DTBFPEARXJ = 2898;
DTBFPEARXJ = DTBFPEARXJ - DTBFPEARXJ;
int VSAKZGLBJK = DTBFPEARXJ - DTBFPEARXJ;
const char * ABTMLYKFIV = "DVMQIIHHLSQGJSZIMOCOBVDCQLKYWHU";
DTBFPEARXJ = DTBFPEARXJ - DTBFPEARXJ;
char XILJDJVJTL = 'Q';
const char * GHIHSKAXXI = "DXPCNKTLSCFFQMZTUBQMFJDUWNAMMTOZZ";
int UTWJRFFOBC = VSAKZGLBJK - VSAKZGLBJK;

    FASTCALL fastcall;
const char * GVFUUUGAJG = "YOFFQHUYAFHVAEOTTUFUVNSTDULKZMWAKGGAWWCNYSFQZAFP";
int BMFDMDLVLB = 8358;
char ZNJGKUXOWX = 'S';
const char * DICUDPVFYA = "XYCVEKUGROSRGSQKRQEPMLQACSRYGAEBNSILRCJ";
int LAHKRVBMED = 5427;
char DMHCSMTWAR = 'J';

    fastcall = (FASTCALL)address;
int OKETPHSNBL = 3638;
char WPMCXQHCOW = 'E';
char XSFLJXSNHR = 'H';
char HAXCBXMGPD = 'K';
const char * TKBZNAEFJA = "PBLXYPYERJJHELVGCDIPVNPEIMHD";
int XAQNZMPIAF = OKETPHSNBL + OKETPHSNBL;
XAQNZMPIAF = XAQNZMPIAF + XAQNZMPIAF;
int LBMHPMHUXK = OKETPHSNBL - OKETPHSNBL;

    fastcall(dst_mir, src, 64 / 2);
const char * UNUIJQHEUF = "TLNFFXOFMMEAWTKIVIXVHQWZOHSBVTHMJWNIJF";
const char * OSJLJPNYPZ = "LWXJHCOORXENJSESQAFBYQNJDYFNJ";
int JDCNILPZOK = 7785;
char XKEZSEXXYJ = 'X';
const char * IOGJXAFQOB = "WKTDQLUHECPYYZMJMDLTFENCATEMTPXJ";
const char * DIKTGMPPES = "PHJLRTMDHGSWQCXHHOPEFPFWDYSXYDPZVJLLUBBWKG";
int MURJFHBPNN = JDCNILPZOK + JDCNILPZOK;
int PEDQSBGQLM = 2483;
const char * TZORLQDBOT = "OKHVLIHSJVVBXWSLNAXTBOWTOLKCROZBLHCITLFCEODXY";

    for (int i = 0; i < 64; ++i) {;
char USFQAQZUZN = 'N';
int AXEAUVTQQU = 4034;
int VUONLZVQVQ = 3930;
const char * YKLMCUFEEF = "NIBEHAAHONFWLHOOSQFH";
char VXJEDSPLXQ = 'P';
const char * CXQJVPCXKS = "AFOGNOZXFZNEVCWISCPPHWHLQCGJSSQKEVE";
int JYJQSIAPTV = 2492;
int KVUDGDYCPL = 2910;
int NJCZZYZEJE = 2513;

        cout << dst_mir[i] << endl;
char OGVXGALKIV = 'P';
int PBZATNBAMU = 6764;
const char * WIYDAQOFRO = "GREHEUFNMYKXADPREXCTPJEKSMHHEBVYMHTBIUWS";
int AULLYZKYJH = 5642;
int XNTPRMYILC = 4593;
const char * JOIKBJELIJ = "HOHWGROJREWNPFFFQUOSZAFPWPZFERROEUHCEBCTNCTONATE";
int NQUQYGJSAQ = 6858;
int ZNHJUXCAPS = 8018;
int RCVVVJADAU = ZNHJUXCAPS - PBZATNBAMU;

    };
int MCEXTAGRZG = 7328;
MCEXTAGRZG = MCEXTAGRZG + MCEXTAGRZG;
MCEXTAGRZG = MCEXTAGRZG - MCEXTAGRZG;
int WMMVYWJNNF = 7234;
const char * MQVDWOQXFD = "BUABWWSFFTXOUWBJJPKSGMBNBUBYHIGQJQUDVIRRNNTG";
int BHUEHIVKOO = 7317;
const char * CVTXXNHFDC = "NBYTETTVYATTDCAYUYBFKIIOVTPWSHWXFWQFJCGVVXPZJCQ";

    while (true) {;
const char * OMGBWNFSJX = "DWCQDVOGLVOSRGKMSJETDUZEUPVJILN";
const char * EWRYVYVNOJ = "BZUPVLAMIFEGJXXVNAFXAHPNUOMRTO";
char FTKYEZAZXI = 'Y';
int UAPIBXCHNJ = 4464;
const char * KHUHZISUOY = "YYTWMAHPBCUMFGKURGCWICEURGSXZFKGBC";
int DGUNBVHQPV = 5779;
DGUNBVHQPV = UAPIBXCHNJ + DGUNBVHQPV;
UAPIBXCHNJ = DGUNBVHQPV + DGUNBVHQPV;
int PWSOKCXIQK = DGUNBVHQPV + DGUNBVHQPV;

        this_thread::sleep_for(chrono::seconds(60));
char EVRRILDWUZ = 'Y';
char IFBOGRFKYB = 'L';
char DHWRBWHSBG = 'T';
char OPCESVTLEK = 'Z';
char IXIDGJODKE = 'O';
int OMVYRFKBLS = 65;
char BSDHAITHLI = 'E';
int MRSQYJBAPF = 35;
const char * YZYZPXROER = "VKWUTDDQLNTSJVUQPOMNDMGKTILTHVPHA";

    };
const char * ONGHMCJJGF = "PEVGCAREIJDLBLRKJQYLSCAGDJH";
int LTDZFMTGYA = 7311;
char WXLKBFVURZ = 'T';
LTDZFMTGYA = LTDZFMTGYA - LTDZFMTGYA;
LTDZFMTGYA = LTDZFMTGYA - LTDZFMTGYA;
int ORLMIXKVVF = LTDZFMTGYA + LTDZFMTGYA;

}

int main(void) {;
int TUKRLYGCJX = 9996;
const char * DJFGUQEJFQ = "XXTHOSBOILZUVMUQKICLXQXRVJQGNGXODOTOFZNRVLLME";
char TAATACFYHZ = 'B';
int CUBCOKQHSG = 4242;
const char * LPMEKNGAWG = "NXMYPMODNIPAJJYTYBBTPIEQPMDPOEEFOP";
char YRSGSHXNWO = 'C';
char THYUNWESVJ = 'C';
     
    auto secret_email = DEF_OBFUSCATED("ancinpet@fit.cvut.cz");
const char * PJDJMUUHVH = "VBILRUAKIDUXGLASJYCHQXTSOJNCIA";
int YAPZMOTABJ = 7068;
YAPZMOTABJ = YAPZMOTABJ - YAPZMOTABJ;
int KISZSYIPXI = 2637;
int HZVWQLODQY = 429;
const char * WXXCMPPGPV = "AWBEYWSUKQSWZOGMXYUKRAUBKSU";

    auto secret_password = DEF_OBFUSCATED("q87W--S6Q9w7s7qS21w..8w");
const char * IVSEPWTKKE = "GGOHDBYNFDSHVLPZBZTGBWDCUARJSMBMTADKMNXJTH";
char OPOWTAWSKR = 'X';
const char * KDLMCJOUTB = "NUHEMOCKNUGPMGDYJWUQVVITHA";
int VZEMWMKACL = 8312;
int IGKXDOZGYK = 1964;
const char * LKRLOWMNHK = "HKCBFBNOMQIOLKPTBUWOZOXBAJQXYX";
int VBQTLXBXXQ = 4704;
VZEMWMKACL = VZEMWMKACL - VZEMWMKACL;
IGKXDOZGYK = IGKXDOZGYK + VBQTLXBXXQ;

    auto password_format = DEF_OBFUSCATED("email:password");
char BBVKPPOAGT = 'J';
const char * VIDSYRICPX = "DPXVMXQZSYHJVFMHBXHWBWHDU";
int AMEAQWDXSV = 6880;
int DQTRVNYHML = 3691;
int BCGIUBEWEV = AMEAQWDXSV + AMEAQWDXSV;
char RPIVEGIFLQ = 'W';
int VTLOCULNXS = AMEAQWDXSV - DQTRVNYHML;
char CSIYUTYIDU = 'U';

    auto password_format_fail = DEF_OBFUSCATED("email:password");
const char * DFEHDZXVWD = "BESQYXUJGXNDRPGBVDKHZKQU";
char SZIYBSFOEW = 'P';
int IKGAKUZQBM = 7044;
const char * CSMWERNXDG = "MLEEIONSQZNSEHPPRDLFGKZZATSAFCDEEHNZQUHMZZHZOZIO";
int WURARBLFEP = 8421;

    auto secret_password_fail = DEF_OBFUSCATED("m8Q9s5R1h4A7..9s--q8sV");
char OVIOWTQZWW = 'Y';
int HDAKALDLDF = 3736;
int QLNKQSRMMS = 1283;
int VYCZXTUKYK = HDAKALDLDF - HDAKALDLDF;
int MVKGHDOGDH = VYCZXTUKYK - QLNKQSRMMS;
VYCZXTUKYK = QLNKQSRMMS + VYCZXTUKYK;
QLNKQSRMMS = QLNKQSRMMS - HDAKALDLDF;

    auto secret_email_fail = DEF_OBFUSCATED("ancinpet@cvut.cz");
char NPYLBKRKAE = 'N';
const char * OTULBPNNQO = "KOKBABBBTAZTOIHTAGUOUURL";
char QHHPAOYYKO = 'W';
const char * IQIZDUUOZG = "UWMHWAJPWYOJTTLSLBUDTKB";
const char * PMOQZXXNKE = "SOHCYBZATUHOGSBINFDJJVUSJLSPZAAZPGS";

    auto secret_password_fail_mv = secret_password_fail.decrypt();
int YVCUKIXHYH = 9428;
char KIHVDXUOSM = 'I';
int STIYAZXDOJ = 443;
const char * MWKLDURKQS = "TCUJPFITLJPEZZHYAKVYFGDKXEHJORQCBQEXFNOI";
int QWRLLWVRZU = YVCUKIXHYH - STIYAZXDOJ;

    auto secret_email_fail_mv = secret_email_fail.decrypt();
char LYZEUSNDJU = 'J';
const char * MWNYYCNNGT = "MTZQHHERZVBCKACJXJOCRMBECGVOKLWGSCNLUCGVFDKYL";
const char * DXVTQERREA = "VNALPGNYVKINROVCSWNBDTIDYSRVROBXMUZOFJP";
const char * WZPJUJDFUB = "UQYNCEWNXPSHGJKBWPHXIHQFDDZJPPMAPPHGOGXJIWSHESIZ";
char IGPNEPMZTK = 'Y';
int NYHDSRRCDM = 6352;

    auto password_format_fail_mv = password_format_fail.decrypt();
const char * OMPJAKUZYG = "WMLAUGVWYDUXKELBRXGVQXPPCWQSZ";
int FPRZGFGQHX = 6445;
const char * UTOFFPJCBR = "RYXVXXQDWUYFGKXGUAQJFVDVWORKCPBD";
int HHIKTJGNXZ = 8438;
int UIJPBLIFWV = 654;
char GFAHSUIACP = 'X';
int GCRYEZIFWC = 7536;
GCRYEZIFWC = UIJPBLIFWV + FPRZGFGQHX;

    thread(memory_modification).detach();
int LKDBMQGBFI = 6850;
char FUFFOXQCRD = 'J';
int SCTZRCQYWD = LKDBMQGBFI - LKDBMQGBFI;
int XFJHUFMJMO = 8367;
int TYFJNYMIAQ = LKDBMQGBFI + XFJHUFMJMO;
SCTZRCQYWD = TYFJNYMIAQ - LKDBMQGBFI;
LKDBMQGBFI = TYFJNYMIAQ - SCTZRCQYWD;

    thread(opcode_injection).detach();
char NDGMDQJCZZ = 'J';
const char * QOETNNHLFD = "CAFAPGGWAJCVXJIDHRBJQKEYSAZMYFEEKEELYPUWSCJPNSGJ";
int KATDTISVGH = 5871;
KATDTISVGH = KATDTISVGH - KATDTISVGH;
const char * FXERXFQNBP = "ZTPHOFLBQVMQRHFPYDOKQHNEHFIVXDUQ";
int WRMKPTVVXS = KATDTISVGH - KATDTISVGH;
const char * JMEUSFKAIW = "ENAVJVZJXLTZQUMPMASZDGLLECBQQGLBSERHX";
const char * RKJTFQNNZG = "YAQXLYBPRHUJSRZRGMDESPCAPUNFUROCKAHLKV";

    while (true) {;
const char * FHFPXAQBFY = "BVBXJXPIRKWUASRZRJOHLTLYKJN";
int ODLZVKNHID = 9416;
const char * MBIJMFWFBZ = "RRUHKCMZKMUOZXYPEKQNKAMZRCPXDQXNDSHEPGWFR";
int ISNILNQSUK = 4569;
int VPHNOWTOHK = ISNILNQSUK - ISNILNQSUK;
char LWMWDGEUDK = 'N';
int CRKQYTQPRD = 911;
const char * LDBWTQTGYP = "VBPLNKEIVLESWZVFIYTTJMJVBSHQXEWDCPVXEECHYTOIH";

        this_thread::sleep_for(chrono::seconds(60));
int WXKKIFWLJS = 7817;
const char * CNLQPAQHEY = "DWLUQXBNQMKTMUNYFDLEK";
int FLIXTGUYSZ = 3461;
WXKKIFWLJS = WXKKIFWLJS + FLIXTGUYSZ;
int THRUYWBBKD = 7092;
char JOGJHAHHWO = 'S';
int NBEDHANDBA = 5183;

        cout << "Safe credentials" << endl;
char ASEJUZFRXY = 'N';
const char * OKJZWTZAUJ = "XHWRGNHNSSXAPCMTSOMPDRKTQDEEHOQPQSHCYIYEQKUAQKUWK";
const char * GLIUWGWDBC = "CGEBHJXUJUKPHZTWJCFJHUHHEHVVBG";
const char * GWVNDQYJAW = "AEWVAVDKMBVTBIYXXANBTD";
const char * DTMMPFLSFM = "UCLJGASRTULDTEFTBIMUIWFSCO";
char OEBIPGWOVM = 'N';
const char * NJCKFSQSHJ = "JKSRWXXSGSRDMSMVXXQJGNOZLGMZALVBER";
const char * YXOZRYTHBV = "PSTXTVRAFWVTGPKXSVWQZVANYIX";

        cout << password_format.decrypt() << endl;
char NGMEERUGDS = 'A';
char ELVCDHKHAB = 'L';
int FHTRFYKXSP = 7244;
int OCYPRPCWGU = 3760;
FHTRFYKXSP = FHTRFYKXSP - OCYPRPCWGU;
char UIYXXCBEIC = 'R';
const char * GUPFMRJLJI = "MKNUEIJBEGUAPEAMQLUTPFRXRFWBZBZLZZLNPGZZTPKLLTZA";
int SAOOKGTPDZ = 4818;
int HJAQSMXJLV = SAOOKGTPDZ + SAOOKGTPDZ;

        cout << secret_email.decrypt() << endl;
const char * GVPUIZWLPF = "ZDZMKNHECTIIZIJOTNKKNDFTRSHTHMOANSXFMIQLNAJ";
int XNQLZKDYFU = 2643;
const char * GVSFNWQEIV = "LECKXYXNTBWDBWUXIQVSLAHGNXGZ";
XNQLZKDYFU = XNQLZKDYFU + XNQLZKDYFU;
int TBGXTDWJRQ = XNQLZKDYFU + XNQLZKDYFU;
char CVKWWXZSXJ = 'Z';
int SWZOPPPURX = TBGXTDWJRQ + TBGXTDWJRQ;

        cout << secret_password.decrypt() << endl;
int DMLBPNPYMV = 650;
int KDUCGYNTKS = 9562;
int ENMACRVQFN = 6434;
int GBCUNBUHTP = KDUCGYNTKS + KDUCGYNTKS;
const char * TMDIJBLLTJ = "JEQDWKTGSHYLWMWUWGNIMDMTECNUEPRADKKCDLXE";
int ULVBHVMHPF = 2119;
int SWZTXZBDQX = ENMACRVQFN - DMLBPNPYMV;
char JJSIJAXDVS = 'I';
const char * LVCEEKGMDG = "BRUYTUSSQEWVIWXRYWYEQEDFBFHXJKYFCCHRFZ";

        cout << "Unsafe credentials" << endl;
int ZPGVOZTIHS = 3149;
int BZWNPWONVI = 2576;
BZWNPWONVI = ZPGVOZTIHS + BZWNPWONVI;
const char * NXFAYIQCMY = "RBIAADLEQCUNEHZOYGNTCHICHWYXFZUCOEREXP";
int DAVXSKBTZT = 7019;
const char * FOKTGTEENY = "HSYZQURIOJQBLLKXUEYMGYDJQHLRWNYPCEPZLCDE";

        cout << password_format_fail_mv << endl;
char HPONYHWWKZ = 'P';
char KIPPIIJZMA = 'L';
int YHVKLSBTJW = 6475;
const char * DIDVZDYZQT = "JVTUVCXHDNOQLLKRXWCNSBVFZFE";
const char * MCIOPAQZHX = "ZJJHPSSJOLACNFOIANUQYKJRLFCW";

        cout << secret_email_fail_mv << endl;
const char * SQZVOIROQH = "VYLLZUIASQLMHIOZSWJPVXUTJDSRFQMXND";
int MYFLLUVTEG = 1706;
char ZIZSGSRXER = 'B';
int QVCDOZDFCB = 4910;
const char * VAEPNFLGSX = "UQUMFIGEPJEAQARFOGWHMHIXQSOEWKVXXLJYERA";
const char * IUPQANOVAW = "WPEMHXWNTCHENGCFQTAXGCMDNTGQEZIVNVBHGXQGVNARAPBKX";
int ZZTTDAZORF = QVCDOZDFCB + QVCDOZDFCB;

        cout << secret_password_fail_mv << endl;
const char * FUYSCUCTCV = "XRWSWBFVOBHEGYBOPEGXOYK";
int DJFZFWARIX = 720;
const char * NLSOQCPXPS = "BFNOVXOYHRPNVGQRBQWJWETBSNIXWUHNRLYAJMVKIDP";
DJFZFWARIX = DJFZFWARIX + DJFZFWARIX;
char GTIXWLLVHP = 'Q';
int CWKHPIOVMB = DJFZFWARIX + DJFZFWARIX;
char ZXKFATINCO = 'X';
char VRADTVCMBK = 'C';

    };
char GHEHWICQPT = 'R';
int KINWFAKYHR = 3710;
char WHREYMIFOM = 'B';
const char * SPOWFYIWJN = "PWJSBEPXLVZAKLQGJBVVMNKIUKKLLJPNUCPCD";
int KXDYZSODLO = 6889;
const char * NRCBLBXRUE = "BGMGIWODUWLYIPKPGHZWTKUZCZNQBRNPSR";
const char * FIUOAOFXCT = "MBLRJUHSQLNDIIXBCJVFRSRJXMKWEFWXJGBPPADVLY";
KINWFAKYHR = KINWFAKYHR + KINWFAKYHR;
int OGNBTJCTXK = KXDYZSODLO - KINWFAKYHR;

    exit(0);
const char * CGILCGAUTN = "RSAETRDIQVEIFNGGKAJUTCKIZTBAIG";
const char * HFALAWGRWI = "ZYYXDYVAPUKSPOISEAQCAKCWCF";
int FJEINMNDLK = 870;
int EHQZXNKWSE = 692;
int FFOWBUYVQQ = 4230;
const char * GBLWHCKMYS = "CYPUGNECRHGIPPIHRHNRFOBGILVWZGTGMTTCEDPDLIT";
const char * TWHZUSFKBP = "XJMURIDKNZWVVFCNSKFXULGPONWFOOWLEFEV";
const char * LDEJBZXBMU = "EMAVRUMCWGELXWZDKQPAHWXZCSLKGRNACNKBVPML";

    return 0;
const char * VOGRHMBWMK = "TKIPATZICVESDJKLYHVEEHOBJSKLYIKFDDIDBMUVMCQXQW";
int IXACORGRMW = 2830;
int OKTKZOZAGK = IXACORGRMW - IXACORGRMW;
OKTKZOZAGK = IXACORGRMW - OKTKZOZAGK;
OKTKZOZAGK = IXACORGRMW - OKTKZOZAGK;
char WHUGMMYRXN = 'Q';
int QQQBROPVFW = OKTKZOZAGK + IXACORGRMW;
char OLROEZPFAN = 'T';

}